2022-10-17 12:40:47,157	INFO trainable.py:160 -- Trainable.setup took 25.051 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2022-10-17 12:40:47,160	WARNING util.py:65 -- Install gputil for GPU system monitoring.
Main training step 0
training epoch 0 137 0.8 -0.030656934306569208
Main training step 1
training epoch 1 292 0.8 0.6277397260273972
Main training step 2
training epoch 2 319 0.8 0.6420062695924764
Main training step 3
training epoch 3 281 0.8 0.6740213523131673
Main training step 4
training epoch 4 321 0.8 0.7090342679127725
Backend QtAgg is interactive backend. Turning interactive mode on.
['self', 'mode', 'state', 'agent', 'v', 'Q', 'pi', 'policy', 'v2Q', 'gamma', 'method_label', 'label']
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 175, in <module>
    res.append(wfun(a))
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 119, in my_experiment
    train(env, VINNetwork(env, trainer), num_episodes=10) #__init__() missing 3 required positional arguments: 'num_outputs', 'model_config', and 'name'
TypeError: __init__() missing 3 required positional arguments: 'num_outputs', 'model_config', and 'name'
Traceback (most recent call last):
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adams\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\adams\.vscode\extensions\ms-python.python-2022.16.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 175, in <module>
    res.append(wfun(a))
  File "c:\Users\adams\OneDrive\Desktop\Masters\MasterThesis\mavi-main\src\raya3c\example_vin.py", line 119, in my_experiment
    train(env, VINNetwork(env, trainer), num_episodes=10) #__init__() missing 3 required positional arguments: 'num_outputs', 'model_config', and 'name'
TypeError: __init__() missing 3 required positional arguments: 'num_outputs', 'model_config', and 'name'